---
minimum_pre_commit_version: '2'
exclude: |
  (?x)^(
    notebooks/.* |
    scripts/.* |
    .github/.*
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent, '4']
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-merge-conflict
      - id: requirements-txt-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-tabs
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        require_serial: true
        args: ["--profile", "black"]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
